//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recently reported.
        /// </summary>
        public static string _24Report {
            get {
                return ResourceManager.GetString("24Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string activeCases {
            get {
                return ResourceManager.GetString("activeCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do not leave your home except to seek medical care, stock up on food, medicine or other important household items.
        /// </summary>
        public static string AdvD1 {
            get {
                return ResourceManager.GetString("AdvD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep at least 1 meter (3 feet) away from you and others.
        /// </summary>
        public static string AdvD2 {
            get {
                return ResourceManager.GetString("AdvD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use face masks in public places. The use of masks should be part of a comprehensive strategy that includes measures to eliminate transmission and save lives; the use of a mask is not sufficient to provide an adequate level of protection against COVID-19.
        /// </summary>
        public static string AdvD3 {
            get {
                return ResourceManager.GetString("AdvD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hands touch many surfaces and can lift viruses. Once contaminated, the hands can transfer the virus to the eyes, nose, or mouth.
        /// </summary>
        public static string AdvD4 {
            get {
                return ResourceManager.GetString("AdvD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cover your mouth and nose with a tissue when you cough or sneeze, or use the inside of your elbow.
        /// </summary>
        public static string AdvD5 {
            get {
                return ResourceManager.GetString("AdvD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wash your hands often with soap and water for at least 20 seconds, especially after you&apos;ve been in a public place, or after blowing your nose, coughing, or sneezing.
        /// </summary>
        public static string AdvD6 {
            get {
                return ResourceManager.GetString("AdvD6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use an alcohol-based hand sanitizer with at least 60% alcohol, and cover the entire surface of your hands by rubbing them together until dry.
        /// </summary>
        public static string AdvD7 {
            get {
                return ResourceManager.GetString("AdvD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frequently clean and disinfect daily contact surfaces, i.e. tables, door knobs, light faucets, countertops, handles, desks, telephones, keyboards, toilets, faucets, and sinks.
        /// </summary>
        public static string AdvD8 {
            get {
                return ResourceManager.GetString("AdvD8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Watch for the onset of symptoms. Follow the care instructions from your health care provider and local health department. Local health authorities will give you directions on how to check your symptoms and report the information.
        /// </summary>
        public static string AdvD9 {
            get {
                return ResourceManager.GetString("AdvD9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advices.
        /// </summary>
        public static string advices {
            get {
                return ResourceManager.GetString("advices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stay at home.
        /// </summary>
        public static string AdvT1 {
            get {
                return ResourceManager.GetString("AdvT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Practice social distancing.
        /// </summary>
        public static string AdvT2 {
            get {
                return ResourceManager.GetString("AdvT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wear a face mask.
        /// </summary>
        public static string AdvT3 {
            get {
                return ResourceManager.GetString("AdvT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avoid touching your eyes, nose and mouth.
        /// </summary>
        public static string AdvT4 {
            get {
                return ResourceManager.GetString("AdvT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cover your nose and mouth when you cough and sneeze.
        /// </summary>
        public static string AdvT5 {
            get {
                return ResourceManager.GetString("AdvT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wash your hands frequently.
        /// </summary>
        public static string AdvT6 {
            get {
                return ResourceManager.GetString("AdvT6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use alcohol or alcohol gel.
        /// </summary>
        public static string AdvT7 {
            get {
                return ResourceManager.GetString("AdvT7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean and disinfect.
        /// </summary>
        public static string AdvT8 {
            get {
                return ResourceManager.GetString("AdvT8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monitor your health daily.
        /// </summary>
        public static string AdvT9 {
            get {
                return ResourceManager.GetString("AdvT9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Follow the advice of the relevant national and local health authorities or your employer on how to protect yourself and others.
        /// </summary>
        public static string bannerDescription {
            get {
                return ResourceManager.GetString("bannerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let&apos;s fight COVID-19 together!.
        /// </summary>
        public static string bannerTitle {
            get {
                return ResourceManager.GetString("bannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press to know more about COVID-19.
        /// </summary>
        public static string btnExternalInfo {
            get {
                return ResourceManager.GetString("btnExternalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy me a coffee!.
        /// </summary>
        public static string buyCoffee {
            get {
                return ResourceManager.GetString("buyCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Designed by Freepik.
        /// </summary>
        public static string byFreepik {
            get {
                return ResourceManager.GetString("byFreepik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Percentage of cases.
        /// </summary>
        public static string casesPercentage {
            get {
                return ResourceManager.GetString("casesPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmed.
        /// </summary>
        public static string confirmedCases {
            get {
                return ResourceManager.GetString("confirmedCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the problem persists, contact the developer.
        /// </summary>
        public static string contatDeveloper {
            get {
                return ResourceManager.GetString("contatDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continents.
        /// </summary>
        public static string continents {
            get {
                return ResourceManager.GetString("continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Countries.
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See statistics for each country.
        /// </summary>
        public static string countriesStats {
            get {
                return ResourceManager.GetString("countriesStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Covid-19 Tests.
        /// </summary>
        public static string covidTests {
            get {
                return ResourceManager.GetString("covidTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Critical.
        /// </summary>
        public static string critical {
            get {
                return ResourceManager.GetString("critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tests performed.
        /// </summary>
        public static string currentTest {
            get {
                return ResourceManager.GetString("currentTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data source.
        /// </summary>
        public static string dataInfo1 {
            get {
                return ResourceManager.GetString("dataInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All the information shown in the application comes from the NOVEL COVID API service. This service provides a wide range of detailed information about the COVID-19 pandemic which ranges from global data descriptions to city/region specific data. It also provides official government data for some countries. .
        /// </summary>
        public static string dataInfo2 {
            get {
                return ResourceManager.GetString("dataInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For more information see official NOVEL COVID API documentation..
        /// </summary>
        public static string dataInfo3 {
            get {
                return ResourceManager.GetString("dataInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See official documentation.
        /// </summary>
        public static string dataInfoBtn {
            get {
                return ResourceManager.GetString("dataInfoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deaths.
        /// </summary>
        public static string deathsCases {
            get {
                return ResourceManager.GetString("deathsCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string developer {
            get {
                return ResourceManager.GetString("developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About Covid-Info.
        /// </summary>
        public static string devInfo1 {
            get {
                return ResourceManager.GetString("devInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello! My name is Rafael Ibañez..
        /// </summary>
        public static string devInfo2 {
            get {
                return ResourceManager.GetString("devInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COVIDINFO is a personal project, created to provide official and reliable information on the progress of the COVID-19 pandemic, showing the progress of the number of cases in each country and the number of cases worldwide..
        /// </summary>
        public static string devInfo3 {
            get {
                return ResourceManager.GetString("devInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For any kind of information or suggestion you can send me a mail to this address: .
        /// </summary>
        public static string devInfo4 {
            get {
                return ResourceManager.GetString("devInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donate to the COVID-19 Response Fund.
        /// </summary>
        public static string DONATIONS {
            get {
                return ResourceManager.GetString("DONATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to the server. Please, try again!
        ///
        ///If the problem persists you can report to the developer: rafael.ideveloper@gmail.com.
        /// </summary>
        public static string errorConectionServer {
            get {
                return ResourceManager.GetString("errorConectionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Questions and Answers about Coronavirus Disease (COVID-19).
        /// </summary>
        public static string FAQS {
            get {
                return ResourceManager.GetString("FAQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Global Info.
        /// </summary>
        public static string globalInfo {
            get {
                return ResourceManager.GetString("globalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official information from the Government of the Republic of El Salvador..
        /// </summary>
        public static string goesInfo {
            get {
                return ResourceManager.GetString("goesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If this app has been to your liking.
        /// </summary>
        public static string greatApp {
            get {
                return ResourceManager.GetString("greatApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guide.
        /// </summary>
        public static string guide {
            get {
                return ResourceManager.GetString("guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vectorized images are.
        /// </summary>
        public static string imgVector {
            get {
                return ResourceManager.GetString("imgVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last update: .
        /// </summary>
        public static string lastUpdta {
            get {
                return ResourceManager.GetString("lastUpdta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Less affected countries.
        /// </summary>
        public static string lessAffectedCountries {
            get {
                return ResourceManager.GetString("lessAffectedCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are problems with your internet connection. Please, try again!.
        /// </summary>
        public static string limitedConnection {
            get {
                return ResourceManager.GetString("limitedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Most affected countries.
        /// </summary>
        public static string mostAffectedcountries {
            get {
                return ResourceManager.GetString("mostAffectedcountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tips for the public about the rumors about the new coronavirus.
        /// </summary>
        public static string MYTHS {
            get {
                return ResourceManager.GetString("MYTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Internet connection.
        /// </summary>
        public static string noInter {
            get {
                return ResourceManager.GetString("noInter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official information .
        /// </summary>
        public static string officialInformation {
            get {
                return ResourceManager.GetString("officialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official information.
        /// </summary>
        public static string oficialInformation {
            get {
                return ResourceManager.GetString("oficialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select sort.
        /// </summary>
        public static string orderBy {
            get {
                return ResourceManager.GetString("orderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovered.
        /// </summary>
        public static string recoveredCases {
            get {
                return ResourceManager.GetString("recoveredCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        public static string searchPlaceHolder {
            get {
                return ResourceManager.GetString("searchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is recommended that people who suffer mild symptoms and have a good general health condition are confined at home.
        /// </summary>
        public static string sintomasCDescription {
            get {
                return ResourceManager.GetString("sintomasCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Common Symptoms.
        /// </summary>
        public static string sintomasCTitle {
            get {
                return ResourceManager.GetString("sintomasCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you have severe symptoms, seek immediate medical attention. However, you should always call your doctor or healthcare center before showing up at the location in question.
        /// </summary>
        public static string sintomasGDescription {
            get {
                return ResourceManager.GetString("sintomasGDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serious Symptoms.
        /// </summary>
        public static string sintomasGTitle {
            get {
                return ResourceManager.GetString("sintomasGTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People who become infected begin to have symptoms within 5 to 6 days after they become infected, but can take up to 14 days.
        /// </summary>
        public static string sintomasHDescription {
            get {
                return ResourceManager.GetString("sintomasHDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usual Symptoms.
        /// </summary>
        public static string sintomasHTitle {
            get {
                return ResourceManager.GetString("sintomasHTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Learn more on the World Health Organization website.
        /// </summary>
        public static string sintomasSource {
            get {
                return ResourceManager.GetString("sintomasSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stay home!.
        /// </summary>
        public static string stayhome {
            get {
                return ResourceManager.GetString("stayhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Symptoms.
        /// </summary>
        public static string symptoms {
            get {
                return ResourceManager.GetString("symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fever.
        /// </summary>
        public static string symptoms1 {
            get {
                return ResourceManager.GetString("symptoms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skin rashes or loss of color on the fingers or toes.
        /// </summary>
        public static string symptoms10 {
            get {
                return ResourceManager.GetString("symptoms10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficulty breathing or feeling short of breath.
        /// </summary>
        public static string symptoms11 {
            get {
                return ResourceManager.GetString("symptoms11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chest pain or pressure.
        /// </summary>
        public static string symptoms12 {
            get {
                return ResourceManager.GetString("symptoms12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inability to speak or move.
        /// </summary>
        public static string symptoms13 {
            get {
                return ResourceManager.GetString("symptoms13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dry cough.
        /// </summary>
        public static string symptoms2 {
            get {
                return ResourceManager.GetString("symptoms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fatigue.
        /// </summary>
        public static string symptoms3 {
            get {
                return ResourceManager.GetString("symptoms3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Body aches and pains.
        /// </summary>
        public static string symptoms4 {
            get {
                return ResourceManager.GetString("symptoms4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sore Throat.
        /// </summary>
        public static string symptoms5 {
            get {
                return ResourceManager.GetString("symptoms5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diarrhoea.
        /// </summary>
        public static string symptoms6 {
            get {
                return ResourceManager.GetString("symptoms6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conjunctivitis.
        /// </summary>
        public static string symptoms7 {
            get {
                return ResourceManager.GetString("symptoms7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Headache.
        /// </summary>
        public static string symptoms8 {
            get {
                return ResourceManager.GetString("symptoms8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loss of sense of smell or taste.
        /// </summary>
        public static string symptoms9 {
            get {
                return ResourceManager.GetString("symptoms9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total cases.
        /// </summary>
        public static string totalCases {
            get {
                return ResourceManager.GetString("totalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please try again!.
        /// </summary>
        public static string tryAgainBTN {
            get {
                return ResourceManager.GetString("tryAgainBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating....
        /// </summary>
        public static string updating {
            get {
                return ResourceManager.GetString("updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View more.
        /// </summary>
        public static string viewmore {
            get {
                return ResourceManager.GetString("viewmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View statistic from each country.
        /// </summary>
        public static string viewSatisticCountries {
            get {
                return ResourceManager.GetString("viewSatisticCountries", resourceCulture);
            }
        }
    }
}
