//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recently reported.
        /// </summary>
        public static string _24Report {
            get {
                return ResourceManager.GetString("24Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string activeCases {
            get {
                return ResourceManager.GetString("activeCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmed.
        /// </summary>
        public static string confirmedCases {
            get {
                return ResourceManager.GetString("confirmedCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the problem persists, contact the developer.
        /// </summary>
        public static string contatDeveloper {
            get {
                return ResourceManager.GetString("contatDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continents.
        /// </summary>
        public static string continents {
            get {
                return ResourceManager.GetString("continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Countries.
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics for each country.
        /// </summary>
        public static string countriesStats {
            get {
                return ResourceManager.GetString("countriesStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COVID19 TESTS.
        /// </summary>
        public static string covidTests {
            get {
                return ResourceManager.GetString("covidTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tests performed.
        /// </summary>
        public static string currentTest {
            get {
                return ResourceManager.GetString("currentTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data source.
        /// </summary>
        public static string dataInfo1 {
            get {
                return ResourceManager.GetString("dataInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All the information shown in the application comes from the NOVEL COVID API service. This service provides a wide range of detailed information about the COVID-19 pandemic which ranges from global data descriptions to city/region specific data. It also provides official government data for some countries. .
        /// </summary>
        public static string dataInfo2 {
            get {
                return ResourceManager.GetString("dataInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For more information see official NOVEL COVID API documentation..
        /// </summary>
        public static string dataInfo3 {
            get {
                return ResourceManager.GetString("dataInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See official documentation.
        /// </summary>
        public static string dataInfoBtn {
            get {
                return ResourceManager.GetString("dataInfoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deaths.
        /// </summary>
        public static string deathsCases {
            get {
                return ResourceManager.GetString("deathsCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string developer {
            get {
                return ResourceManager.GetString("developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about COVIDINFO..
        /// </summary>
        public static string devInfo1 {
            get {
                return ResourceManager.GetString("devInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about COVIDINFO..
        /// </summary>
        public static string devInfo2 {
            get {
                return ResourceManager.GetString("devInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COVIDINFO is a personal project, created to provide official and reliable information on the progress of the COVID-19 pandemic, showing the progress of the number of cases in each country and the number of cases worldwide. If the application has the permissions for access to your GPS location it will show the statistics of the development of the pandemic in your country. .
        /// </summary>
        public static string devInfo3 {
            get {
                return ResourceManager.GetString("devInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For any kind of information or suggestion you can send me a mail to this address: rafael.ideveloper@gmail.com.
        /// </summary>
        public static string devInfo4 {
            get {
                return ResourceManager.GetString("devInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enable your device&apos;s GPS to display your country&apos;s statistics!.
        /// </summary>
        public static string disabledGPS {
            get {
                return ResourceManager.GetString("disabledGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donations(WHO).
        /// </summary>
        public static string DONATIONS {
            get {
                return ResourceManager.GetString("DONATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enable the application&apos;s GPS permissions to display your country&apos;s statistics! This is required only once.
        /// </summary>
        public static string enableGPSPermissions {
            get {
                return ResourceManager.GetString("enableGPSPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Q&amp;A(WHO).
        /// </summary>
        public static string FAQS {
            get {
                return ResourceManager.GetString("FAQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Global Info.
        /// </summary>
        public static string globalInfo {
            get {
                return ResourceManager.GetString("globalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official information  GOES.
        /// </summary>
        public static string goesInfo {
            get {
                return ResourceManager.GetString("goesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last update: .
        /// </summary>
        public static string lastUpdta {
            get {
                return ResourceManager.GetString("lastUpdta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constrained Internet! Can no get last updated data.
        /// </summary>
        public static string limitedConnection {
            get {
                return ResourceManager.GetString("limitedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please connect to an Internet network to get updated data!.
        /// </summary>
        public static string messaConnectToInternet {
            get {
                return ResourceManager.GetString("messaConnectToInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Most affected countries.
        /// </summary>
        public static string mostAffectedcountries {
            get {
                return ResourceManager.GetString("mostAffectedcountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Myths and advices(WHO) COVID-19.
        /// </summary>
        public static string MYTHS {
            get {
                return ResourceManager.GetString("MYTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Internet connection.
        /// </summary>
        public static string noInter {
            get {
                return ResourceManager.GetString("noInter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official information .
        /// </summary>
        public static string officialInformation {
            get {
                return ResourceManager.GetString("officialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official information.
        /// </summary>
        public static string oficialInformation {
            get {
                return ResourceManager.GetString("oficialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovered.
        /// </summary>
        public static string recoveredCases {
            get {
                return ResourceManager.GetString("recoveredCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        public static string searchPlaceHolder {
            get {
                return ResourceManager.GetString("searchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stay home!.
        /// </summary>
        public static string stayhome {
            get {
                return ResourceManager.GetString("stayhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating....
        /// </summary>
        public static string updating {
            get {
                return ResourceManager.GetString("updating", resourceCulture);
            }
        }
    }
}
